apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: web:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: app/aspnetapp/
    git:
      ref: main
      uri: https://github.com/ultraJeff/aspnet-mssql.git
    type: ""
  strategy:
    dockerStrategy: {}
    type: ""
  triggers:
    - type: ConfigChange
status:
  lastVersion: 0
